# Generated by Django 3.2.9 on 2021-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='name',
            field=models.TextField(),
        ),
    ]
