# Generated by Django 3.2.9 on 2021-12-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_contactusmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
