# Generated by Django 3.2.9 on 2021-12-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_contactusmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusmodel',
            name='status',
        ),
    ]
