# Generated by Django 3.2.9 on 2021-11-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
