# Generated by Django 3.2.9 on 2021-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelregistermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelregistermodel',
            name='hotel_image',
            field=models.ImageField(default='none', upload_to='pics/'),
        ),
    ]
