# Generated by Django 3.2.9 on 2021-12-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotelregistermodel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='hotel_location',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='room_facility',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='room_type',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
