# Generated by Django 3.2.9 on 2021-12-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20211202_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetailmodel',
            name='hotel_location',
        ),
        migrations.AlterField(
            model_name='hoteldetailmodel',
            name='hotel_name',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
