# Generated by Django 3.2.9 on 2021-12-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20211203_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelregistermodel',
            name='address',
        ),
    ]
