# Generated by Django 3.2.9 on 2021-12-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotelregistermodel_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetailmodel',
            name='room_details',
        ),
        migrations.RemoveField(
            model_name='hotelregistermodel',
            name='Hotel_name',
        ),
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='contact_no',
            field=models.IntegerField(default='988766544', max_length=20),
        ),
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='email',
            field=models.CharField(default='@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='hotel_location',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
