# Generated by Django 3.2.9 on 2021-12-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20211213_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetailmodel',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=150),
        ),
    ]
