# Generated by Django 3.2.9 on 2021-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20211214_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetailmodel',
            name='contact_no',
            field=models.IntegerField(default='988766544'),
        ),
    ]
