# Generated by Django 3.2.9 on 2021-11-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistermodel',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='userregistermodel',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userregistermodel',
            name='address',
            field=models.TextField(default='None', max_length=90),
        ),
        migrations.AddField(
            model_name='userregistermodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userregistermodel',
            name='dob',
            field=models.DateField(default=20),
        ),
    ]
