# Generated by Django 3.2.9 on 2021-11-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211129_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='address',
            field=models.TextField(default='abc', max_length=90),
        ),
    ]
