# Generated by Django 3.2.9 on 2021-12-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userregistermodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
