# Generated by Django 3.2.9 on 2021-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211209_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
