# Generated by Django 3.2.9 on 2021-12-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_bookmodel_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mail', models.CharField(max_length=50)),
                ('Feedback', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
